name: Trigger auto deployment for container-app-demo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-demo-AutoDeployTrigger-db2db184-862d-4433-9061-d4a43da3acb5.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPDEMO_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.CONTAINERAPPDEMO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPDEMO_REGISTRY_PASSWORD }}
          containerAppName: container-app-demo
          resourceGroup: container-app-rg
          imageToBuild: lanbui/container-app-demo:${{ github.sha }}
          dockerfilePath: Dockerfile

     

